### ISSUE TITLE
Composing grouped gemms leads to precision loss

### ISSUE THREAD

**Issue by kiddyboots216** [tgale96/grouped_gemm#17]
Suppose that we want to compose two grouped gemm operations without materializing the intermediate tensors. This is the typical workflow in LoRA. We might write something like this;

```
r = gg.ops.gmm(gg.ops.gmm(x, w1_A, grouped_gemm_batch_sizes), w1_B, grouped_gemm_batch_sizes)
```

However, this will lead to different results than if we materialized the intermediate result;

```
x = gg.ops.gmm(x, w1_A, grouped_gemm_batch_sizes)
r = gg.ops.gmm(x, w1_AB grouped_gemm_batch_sizes)
```

Example output;
![image](https://github.com/user-attachments/assets/7bb9f9e5-abfa-4c22-bab9-6b7b4c5e4152)

*How do we know this is the one that has precision loss?*

If we train without materializing the intermediate tensors we will observe performance degradation.

**Comment by zainsarwar865** [comment]
Regular matmul compositions have the same precision differences as grouped-gemms.
