### ISSUE TITLE
Grouped GEMM Execution not possible with HW

### ISSUE THREAD

**Issue by ryandeng1** [tgale96/grouped_gemm#4]
I am currently running into an error here: https://github.com/tgale96/grouped_gemm/blob/108009a6cc2ea9f5d712438624518b024f2350d3/csrc/grouped_gemm.cu#L113 when trying to train a Megatron-LM model with megablocks.

I am running this on 2 Nvidia A100 80GB GPUs, with 8 experts. What might be the issue that is causing this?

Thanks in advance.

**Comment by tgale96** [comment]
Hi! Sorry for the delay!

Interesting! Could you share the dimensions of the problem that you're trying to execute? I suspect it is quite large. Even better would be a script to reproduce, which would be very helpful for debugging this :) Thanks!

**Comment by ryandeng1** [comment]
I think it was some kind of installation issue on my end. It seems to work now. Thanks!

**Comment by tgale96** [comment]
Oh excellent! Glad to hear that.
